### PR TITLE
IssueID:1619: clean netmgr_wifi.c private info.

### PR DESCRIPTION
**Pull request by yanxiaoyong-ch**
[Detail]
none

[Verified Cases]
Build Pass: <none>
Test Pass: <none>

### CODE REVIEW

**Comment by skylarCai** [comment]
感谢提交 Pull Requests！
Thanks for submitting a pull request.

**Comment by skylarCai** [comment]
Security Check : c96b185b9f8f115b704a5f9b69ddd26b4def13f6

**Comment by skylarCai** [comment]
auto build success,number:105

**Comment by skylarCai** [comment]
autotest success,number:1248

**Review by jinliangli — APPROVED** [review]
ok

**Review by skylarCai — COMMENTED** [review]
resolve security risk

**Pull request merged**
