### PR TITLE
IssueID:1578:HaaS100 flash driver for new driver framework

### PR DESCRIPTION
**Pull request by wuxn9999**
[Detail]
HaaS100 flash driver for new driver framework.

[Verified Cases]
Build Pass: helloworld_demo@haas100
Test Pass: helloworld_demo@haas100

### CODE REVIEW

**Comment by skylarCai** [comment]
感谢提交 Pull Requests！
Thanks for submitting a pull request.

**Comment by skylarCai** [comment]
Security Check : aa8e07a8e89b9b950079f83c649db5db2d03bebc

**Comment by skylarCai** [comment]
auto build success,number:82

**Comment by skylarCai** [comment]
autotest success,number:1159

**Review by skylarCai — COMMENTED** [review]
no security risk

**Review by victorwangstone — APPROVED** [review]
this new version of HaaS100 flash driver looks good to me

**Review by YiluMao — APPROVED** [review]
It's ok

**Pull request merged**
