### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by skylarCai**

### CODE REVIEW

**Comment by skylarCai** [comment]
感谢提交 Pull Requests！
Thanks for submitting a pull request.

**Comment by skylarCai** [comment]
Security Check : d2f01857c90d4a055a6fffc79043fa080129f551

**Comment by skylarCai** [comment]
auto build success,number:89

**Review by YiluMao — CHANGES_REQUESTED** [review]
Change the GitHub CLI to AliOS Things

**Review by YiluMao — CHANGES_REQUESTED** [review]
Suggest to combine the two patches into one.

**Pull request merged**
