### PR TITLE
fix linksdk whitescan error

### PR DESCRIPTION
**Pull request by victorwangstone**
[Verified Cases]
Build Pass: py_engine_demo
Test Pass: py_engine_Demo

Signed-off-by: wangchengdong.wcd <wangchengdong.wcd@alibaba-inc.com>

### CODE REVIEW

**Comment by skylarCai** [comment]
感谢提交 Pull Requests！
Thanks for submitting a pull request.

**Comment by skylarCai** [comment]
Security Check : 78b684c90b29b243939a1ee9be003ae3632cc6d4

**Comment by skylarCai** [comment]
auto build success,number:87

**Comment by skylarCai** [comment]
autotest success,number:1164

**Review by wuxn9999 — APPROVED** [review]
Looks good to mo.

**Pull request merged**
