### PR TITLE
Add ESP32-C3 support in Haas-Python

### PR DESCRIPTION
**Pull request by HonestQiao**
[Detail]
Support ESP32-C3 4MB and 2MB, with ESP-IDF v4.4

[Verified Cases]
Build Pass: 
Test Pass:

### CODE REVIEW

**Comment by skylarCai** [comment]
感谢提交 Pull Requests！
Thanks for submitting a pull request.

**Comment by skylarCai** [comment]
Security Check : 65c3ec0f9f78b4e23abb503eae3073069ceb2854

**Comment by skylarCai** [comment]
auto build success,number:36

**Comment by skylarCai** [comment]
autotest success,number:1069

**Review by YiluMao — APPROVED** [review]
可以合入

**Review by YiluMao — APPROVED** [review]
可以合入

**Review by YiluMao — APPROVED** [review]
可以合入

**Review by YiluMao — APPROVED** [review]
可以合入

**Review by skylarCai — COMMENTED** [review]
no  security risk

**Pull request merged**
