### PR TITLE
IssueID:1919:Improve PWM and ADC driver framework. Remove old flash device driver framework.

### PR DESCRIPTION
**Pull request by wuxn9999**
- IssueID:1911:Remove old flash device driver framework
- IssueID:1919:improve PWM and ADC driver framework

### CODE REVIEW

**Comment by wuxn9999** [comment]
Cancelled.

**Comment by wuxn9999** [comment]
Reopened.

**Comment by skylarCai** [comment]
感谢提交 Pull Requests！
Thanks for submitting a pull request.

**Comment by YiluMao** [comment]
start build

**Comment by skylarCai** [comment]
手动触发！
感谢 Pull Requests！
Thanks for submitting a pull request.

**Comment by skylarCai** [comment]
Security Check : 5d924f86428be8c73317a1bf30f932e6719f10aa

**Comment by skylarCai** [comment]
auto build fail,number:276

**Comment by YiluMao** [comment]
start build

**Comment by skylarCai** [comment]
手动触发！
感谢 Pull Requests！
Thanks for submitting a pull request.

**Comment by YiluMao** [comment]
start build

**Comment by skylarCai** [comment]
手动触发！
感谢 Pull Requests！
Thanks for submitting a pull request.

**Comment by skylarCai** [comment]
auto build success,number:277

**Pull request merged**
