### PR TITLE
IssueID:1581:access fails after the same I2C device is opened for more than one time

### PR DESCRIPTION
**Pull request by wuxn9999**
[Detail]
Issue description:
Access fails after the same I2C device is opened for more than one time.
Rootcause:
PY-engine does not open an I2C device if it is already opened.
Solution:
Permit multiple open.

[Verified Cases]
Build Pass: <pyengine_demo@haaseduk1>
Test Pass: <pyengine_demo@haaseduk1>

### CODE REVIEW

**Comment by skylarCai** [comment]
感谢提交 Pull Requests！
Thanks for submitting a pull request.

**Comment by skylarCai** [comment]
Security Check : 07e35c26681392ad7f7088b2f88e43b2dc6dc158

**Comment by skylarCai** [comment]
auto build success,number:86

**Comment by skylarCai** [comment]
autotest success,number:1163

**Review by ethanlcz — APPROVED** [review]
looks good to me.

**Review by skylarCai — COMMENTED** [review]
no security risk

**Pull request merged**
