### PR TITLE
stock_alarm, fixes #1842

### LINKED ISSUE #1842: [Feature Request]: add python solution: stock_alarm
### 联系方式
[zy273241@alibaba-inc.com](mailto:zy273241@alibaba-inc.com)

### 新功能描述
增加Python股票涨停报警器案例

### 分支

master (Default)

### PR DESCRIPTION
**Pull request by zy-sunshine**

### CODE REVIEW

**Comment by skylarCai** [comment]
感谢提交 Pull Requests！
Thanks for submitting a pull request.

**Review by victorwangstone — APPROVED** [review]
looks good to me

**Comment by skylarCai** [comment]
start build

**Comment by skylarCai** [comment]
手动触发！
感谢 Pull Requests！
Thanks for submitting a pull request.

**Comment by skylarCai** [comment]
Security Check : d3b6a948b78659d042756e0567db37bb0507c92f

**Comment by skylarCai** [comment]
auto build success,number:230

**Comment by skylarCai** [comment]
autotest fail,number:1724

**Pull request closed without merging**
