### PR TITLE
amp_adapter: improve log

### PR DESCRIPTION
**Pull request by jinliangli**
[Detail]
improve log with ulog system

[Verified Cases]
Build Pass: <py_engine_demo>
Test Pass:  <py_engine_demo>

### CODE REVIEW

**Comment by skylarCai** [comment]
感谢提交 Pull Requests！
Thanks for submitting a pull request.

**Comment by skylarCai** [comment]
start build

**Comment by skylarCai** [comment]
手动触发！
感谢 Pull Requests！
Thanks for submitting a pull request.

**Comment by skylarCai** [comment]
Security Check : c6a2387718022c3371ba2df7a21d8975fb6e7adb

**Comment by skylarCai** [comment]
auto build success,number:239

**Comment by skylarCai** [comment]
autotest fail,number:1747

**Review by yanxiaoyong-ch — COMMENTED** [review]
this looks ok for me

**Pull request merged**
