### PR TITLE
IssueID:1866:设备驱动对VFS的适配层

### PR DESCRIPTION
**Pull request by wuxn9999**
[Detail]
提供通过VFS访问设备驱动的能力。

[Verified Cases]
Build Pass: eduk1_demo
Test Pass: eduk1_demo

### CODE REVIEW

**Comment by skylarCai** [comment]
感谢提交 Pull Requests！
Thanks for submitting a pull request.

**Comment by skylarCai** [comment]
Security Check : ce75ae5883d9faf6defb2e90f9f433b590904941

**Comment by skylarCai** [comment]
auto build success,number:245

**Comment by skylarCai** [comment]
autotest fail,number:1775

**Review by victorwangstone — APPROVED** [review]
looks good to me

**Pull request merged**
