### PR TITLE
restructure lvgl on m5stack and haaseduk1

### PR DESCRIPTION
**Pull request by zhuxinglongbest**
Signed-off-by: zilin.zxl <zilin.zxl@alibaba-inc.com>

### CODE REVIEW

**Comment by skylarCai** [comment]
感谢提交 Pull Requests！
Thanks for submitting a pull request.

**Comment by skylarCai** [comment]
Security Check : 38befa8b5bb907fb66b39043334fd45768c547a4

**Comment by skylarCai** [comment]
auto build fail,number:94

**Review by YiluMao — APPROVED** [review]
I'm ok with this change.

**Comment by skylarCai** [comment]
start build

**Comment by skylarCai** [comment]
手动触发！
感谢 Pull Requests！
Thanks for submitting a pull request.

**Comment by skylarCai** [comment]
auto build fail,number:95

**Comment by skylarCai** [comment]
Security Check : 5a6f36126dc9ebbb45c6ab654d2fc0b66c9f28c3

**Pull request closed without merging**
