### PR TITLE
FingerPrintLockExample

### PR DESCRIPTION
**Pull request by ethanlcz**

### CODE REVIEW

**Comment by skylarCai** [comment]
感谢提交 Pull Requests！
Thanks for submitting a pull request.

**Comment by skylarCai** [comment]
Security Check : 1cf4de5398f38a7e108641b83a437ef89ae743f7

**Review by wzhiyuan-nit — APPROVED** [review]

**Comment by skylarCai** [comment]
auto build success,number:262

**Comment by skylarCai** [comment]
autotest fail,number:1805

**Pull request merged**
