### PR TITLE
IssueID:1685:Python example playing with cats

### PR DESCRIPTION
**Pull request by wuxn9999**
[Detail]
New Python example: playing with cats.

[Verified Cases]
Build Pass: <py_engine_demo>
Test Pass:  <py_engine_demo>

### CODE REVIEW

**Review by yanxiaoyong-ch — COMMENTED** [review]
this looks ok for me

**Comment by skylarCai** [comment]
手动触发！
感谢 Pull Requests！
Thanks for submitting a pull request.

**Comment by skylarCai** [comment]
Security Check : 8a008621ad68147b4e45c6ea91bb7b4feecced64

**Comment by skylarCai** [comment]
auto build success,number:153

**Review by skylarCai — COMMENTED** [review]
no security risk

**Pull request merged**
