### PR TITLE
IssueID:1859:new watchdog driver framework

### PR DESCRIPTION
**Pull request by wuxn9999**
[Detail]
New watchdog driver framework.
New VFS support.
Userspace support.

[Verified Cases]
Build Pass: <helloworld_demo@haaseduk1>
Test Pass: <helloworld_demo@haaseduk1>

### CODE REVIEW

**Comment by skylarCai** [comment]
感谢提交 Pull Requests！
Thanks for submitting a pull request.

**Comment by skylarCai** [comment]
Security Check : 15bfd333e6f2aa43a890a929282f15ba733583ce

**Comment by skylarCai** [comment]
auto build success,number:244

**Comment by skylarCai** [comment]
autotest fail,number:1770

**Review by victorwangstone — APPROVED** [review]
looks good to me

**Pull request merged**
