### PR TITLE
add motion API

### PR DESCRIPTION
**Pull request by ethanlcz**

### CODE REVIEW

**Comment by skylarCai** [comment]
感谢提交 Pull Requests！
Thanks for submitting a pull request.

**Comment by skylarCai** [comment]
Security Check : 2f6f87742f954d40a0f847d0471490b40bc6ae1d

**Comment by skylarCai** [comment]
autotest success,number:1091

**Review by kevin-alibaba — APPROVED** [review]
checked

**Review by skylarCai — COMMENTED** [review]
no security risk

**Pull request merged**
