### PR TITLE
enable freetype for lvgl & remove little_ui dir

### PR DESCRIPTION
**Pull request by zhuxinglongbest**
Signed-off-by: zhuxinglongbest.126.com

### CODE REVIEW

**Comment by skylarCai** [comment]
感谢提交 Pull Requests！
Thanks for submitting a pull request.

**Comment by skylarCai** [comment]
auto build success,number:119

**Comment by skylarCai** [comment]
autotest success,number:1282

**Review by YiluMao — APPROVED** [review]
Looks good to me

**Review by skylarCai — COMMENTED** [review]
no security risk

**Pull request merged**
