### PR TITLE
IssueID:1576:Improve libc_stub

### PR DESCRIPTION
**Pull request by wuxn9999**
[Detail]
Improve termios and ioctl to provide more POSIX compatibility.
On console printing "\r\n" is no longer converted to "\r\r\n".

[Verified Cases]
Build Pass: helloworld_demo@haaseduk1
Test Pass: helloworld_demo@haaseduk1

### CODE REVIEW

**Comment by skylarCai** [comment]
感谢提交 Pull Requests！
Thanks for submitting a pull request.

**Comment by skylarCai** [comment]
Security Check : 2fec54edadb0255c78014a4dfa45999cb214b427

**Comment by skylarCai** [comment]
auto build success,number:81

**Comment by skylarCai** [comment]
autotest success,number:1156

**Review by skylarCai — COMMENTED** [review]
no security risk

**Review by yanxiaoyong-ch — COMMENTED** [review]
this looks ok for me

**Review by YiluMao — APPROVED** [review]
It's ok

**Pull request merged**
