### PR TITLE
rtl872xd: improve log

### PR DESCRIPTION
**Pull request by jinliangli**
[Detail]
remove debug log in wifi connectting

[Verified Cases]
Build Pass: <py_engine_demo>
Test Pass:  <py_engine_demo>

### CODE REVIEW

**Comment by skylarCai** [comment]
感谢提交 Pull Requests！
Thanks for submitting a pull request.

**Comment by skylarCai** [comment]
Security Check : 08fa4c56c8888a10cbd6c193432f5e3cc00218b4

**Comment by skylarCai** [comment]
auto build success,number:231

**Comment by skylarCai** [comment]
autotest fail,number:1733

**Review by yanxiaoyong-ch — COMMENTED** [review]
looks ok for me

**Pull request merged**
