### PR TITLE
add BugReport_zh.yml

### PR DESCRIPTION
**Pull request by skylarCai**

### CODE REVIEW

**Comment by skylarCai** [comment]
感谢提交 Pull Requests！
Thanks for submitting a pull request.

**Comment by skylarCai** [comment]
Security Check : 9f7273161884093573c5ab6e17da9c0161c7cc3b

**Comment by skylarCai** [comment]
auto build fail,number:106

**Review by zy20220224 — COMMENTED** [review]
it looks very good

**Comment by skylarCai** [comment]
auto build fail,number:113

**Comment by skylarCai** [comment]
auto build success,number:115

**Comment by skylarCai** [comment]
autotest success,number:1273

**Pull request merged**
