### PR TITLE
add check for espressif_esp32_c3/esp-idf

### PR DESCRIPTION
**Pull request by HonestQiao**
[Detail]
add check for espressif_esp32_c3/esp-idf

[Verified Cases]
Build Pass:
Test Pass:

### CODE REVIEW

**Comment by skylarCai** [comment]
感谢提交 Pull Requests！
Thanks for submitting a pull request.

**Comment by skylarCai** [comment]
start build

**Comment by skylarCai** [comment]
手动触发！
感谢 Pull Requests！
Thanks for submitting a pull request.

**Comment by skylarCai** [comment]
手动触发！
感谢 Pull Requests！
Thanks for submitting a pull request.

**Comment by skylarCai** [comment]
auto build success,number:43

**Comment by skylarCai** [comment]
autotest success,number:1078

**Comment by yong171966** [comment]
Looks good to me, approved!

**Review by yong171966 — COMMENTED** [review]
not needed for GENERIC_C3 build as espressif_esp32_c3 folder will be deleted later

**Pull request closed without merging**
