### PR TITLE
master

### PR DESCRIPTION
**Pull request by YiluMao**
- IssueID:1515:add value return for all branches
- IssueID:1500:add check for the inet_aton

### CODE REVIEW

**Comment by skylarCai** [comment]
感谢提交 Pull Requests！
Thanks for submitting a pull request.

**Comment by skylarCai** [comment]
Security Check : ef0968518e0900f1e4291b737c9f0c944f66d6f6

**Comment by skylarCai** [comment]
auto build success,number:55

**Comment by skylarCai** [comment]
autotest success,number:1100

**Comment by YiluMao** [comment]
This is a wrong push

**Pull request closed without merging**
