### PR TITLE
add python:weather_forecast, fixes #1838

### LINKED ISSUE #1838: [Feature Request]: add python solution: weather_forecast
### 联系方式

zifu.zh@alibaba-inc.com

### 新功能描述

增加python天气预报案例

### 分支

master (Default)

### PR DESCRIPTION
**Pull request by ZH-21000301**

### CODE REVIEW

**Comment by skylarCai** [comment]
感谢提交 Pull Requests！
Thanks for submitting a pull request.

**Comment by skylarCai** [comment]
Security Check : a4dc4077214d3ee38a845e6a62a456aba7919333

**Comment by skylarCai** [comment]
auto build success,number:227

**Comment by skylarCai** [comment]
autotest fail,number:1704

**Review by zhengfang0571 — COMMENTED** [review]
文字易懂，能操作成功，需要注意GPS模块需要放到室外空旷地，多放一会才能收到数据。

**Review by skylarCai — COMMENTED** [review]
LGFM

**Pull request merged**
