### PR TITLE
haas100: add README.md, fix #1705

### PR DESCRIPTION
**Pull request by jinliangli**
[Detail]
Add README.md

[Verified Cases]
Build Pass: <py_engine_demo>
Test Pass:  <py_engine_demo>

### CODE REVIEW

**Comment by skylarCai** [comment]
感谢提交 Pull Requests！
Thanks for submitting a pull request.

**Comment by skylarCai** [comment]
Security Check : 7316ee8415710c63c213aa0d758830e26e52be9e

**Review by yanxiaoyong-ch — COMMENTED** [review]
this looks ok for me

**Review by skylarCai — COMMENTED** [review]
no security risk

**Pull request merged**
