### PR TITLE
support network interface for haaseduk1. #1642

### PR DESCRIPTION
**Pull request by zy20220224**

### CODE REVIEW

**Review by yong171966 — COMMENTED** [review]
Looks good to me, approved

**Comment by skylarCai** [comment]
感谢提交 Pull Requests！
Thanks for submitting a pull request.

**Comment by skylarCai** [comment]
auto build fail,number:122

**Comment by skylarCai** [comment]
Security Check : 56ebcc091057b81381d6bcb057ba677fa6d85d5f

**Comment by zy20220224** [comment]
abandon

**Pull request closed without merging**
