### PR TITLE
Delete useless code, fixed #1555

### LINKED ISSUE #1555: [Bug Report]: part of code can never be executed
### Contact Details

_No response_

### What happened?

A bug happened!
In file hardware/board/haaseduk1/startup/startup.c: haas_board_init
Execution cannot reach this statement: "krhino_task_sleep(1000ULL);".

### Version

rel_3.3.0 (Main)

### What soultions are you seeing the problem on?

py_engine_demo

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by YiluMao**
Delete useless code in hardware/board/haaseduk1/startup/startup.c

Signed-off-by: yilu.myl <yilu.myl@alibaba-inc.com>

### CODE REVIEW

**Comment by skylarCai** [comment]
感谢提交 Pull Requests！
Thanks for submitting a pull request.

**Comment by skylarCai** [comment]
Security Check : ca984d20465e84fc012b61151a75494989702e12

**Comment by skylarCai** [comment]
auto build success,number:65

**Comment by skylarCai** [comment]
autotest success,number:1129

**Review by yanxiaoyong-ch — COMMENTED** [review]
this looks ok for me

**Review by jinliangli — APPROVED** [review]
Looks good.

**Review by skylarCai — COMMENTED** [review]
no security risk

**Pull request merged**
