### PR TITLE
IssueID:1834:Add driver lib for DDS5188 power meter

### PR DESCRIPTION
**Pull request by wuxn9999**
[Detail]
Add driver lib and doc for DDS5188 power meter.

[Verified Cases]
Build Pass: py_engine_esp32_demo@nodemcu32s
Test Pass: py_engine_esp32_demo@nodemcu32s

### CODE REVIEW

**Comment by skylarCai** [comment]
感谢提交 Pull Requests！
Thanks for submitting a pull request.

**Comment by skylarCai** [comment]
start build

**Comment by skylarCai** [comment]
手动触发！
感谢 Pull Requests！
Thanks for submitting a pull request.

**Comment by skylarCai** [comment]
Security Check : e608a1bb51d72ed518c50cdf9fb6393ae590138e

**Comment by skylarCai** [comment]
auto build success,number:243

**Comment by skylarCai** [comment]
autotest fail,number:1769

**Review by victorwangstone — APPROVED** [review]
looks good to me

**Pull request merged**
