### PR TITLE
IssueID:1579:HaaSEDUK1 flash driver for new driver framework

### PR DESCRIPTION
**Pull request by wuxn9999**
[Detail]
HaaSEDUK1 flash driver for new driver framework.

[Verified Cases]
Build Pass: helloworld_demo@haaseduk1
Test Pass: helloworld_demo@haaseduk1

### CODE REVIEW

**Comment by skylarCai** [comment]
感谢提交 Pull Requests！
Thanks for submitting a pull request.

**Comment by skylarCai** [comment]
Security Check : abf53a37089028dc2f4f92cbc816182848f9b9f1

**Comment by skylarCai** [comment]
auto build success,number:83

**Comment by skylarCai** [comment]
autotest success,number:1160

**Review by yanxiaoyong-ch — COMMENTED** [review]
this looks ok for me

**Review by skylarCai — COMMENTED** [review]
no security risk

**Pull request merged**
