### PR TITLE
add alcohol_detector, fix #1649

### LINKED ISSUE #1649: [Feature Request]: 请增加一个酒驾检测的系统
### Contact Details

_No response_

### What do you want?

feature request

### Version

master (Default)

### PR DESCRIPTION
**Pull request by jinliangli**
[Detail]
add alcohol detector.

[Verified Cases]
Build Pass: <py_engine_demo>
Test Pass:  <py_engine_demo>

### CODE REVIEW

**Comment by skylarCai** [comment]
Security Check : 176ed2e37b6fa3504509de6327c97ffb69856ab0

**Comment by skylarCai** [comment]
autotest success,number:1311

**Comment by skylarCai** [comment]
start build

**Comment by skylarCai** [comment]
手动触发！
感谢 Pull Requests！
Thanks for submitting a pull request.

**Comment by skylarCai** [comment]
手动触发！
感谢 Pull Requests！
Thanks for submitting a pull request.

**Comment by skylarCai** [comment]
Security Check : 0a9ce9b3b2375621924f7f2306bbb85b4a4b01d6

**Comment by skylarCai** [comment]
auto build success,number:134

**Comment by skylarCai** [comment]
autotest fail,number:1331

**Review by yanxiaoyong-ch — COMMENTED** [review]
this looks ok for me

**Review by skylarCai — COMMENTED** [review]
no security risk

**Pull request merged**
