### PR TITLE
IssueID:1557:correct errors in ADS1115 driver and document

### PR DESCRIPTION
**Pull request by ethanlcz**

### CODE REVIEW

**Comment by skylarCai** [comment]
感谢提交 Pull Requests！
Thanks for submitting a pull request.

**Comment by skylarCai** [comment]
Security Check : 2ba929e90c7bff1d9097d40b898c97029beba71b

**Comment by skylarCai** [comment]
auto build success,number:67

**Review by ethanlcz — COMMENTED** [review]
This patch was already verified.

**Comment by skylarCai** [comment]
autotest success,number:1131

**Review by wushengtws — APPROVED** [review]
Done CodeReview

**Review by ethanlcz — COMMENTED** [review]
patch was already verified

**Pull request merged**
