### PR TITLE
haas1000: fix whitescan bugs in hal/wifi_port.c

### PR DESCRIPTION
**Pull request by jinliangli**
[Detail]
Fix whitescan bugs in hal/wifi_port.c
- CWE252: Value returned from a function is not checked for errors
before being used
- CWE125: Out-of-bounds read from a buffer

[Verified Cases]
Build Pass: <py_engine_demo>
Test Pass:  <py_engine_demo

Signed-off-by: Jinliang Li <ljl150821@alibaba-inc.com>

### CODE REVIEW

**Comment by skylarCai** [comment]
感谢提交 Pull Requests！
Thanks for submitting a pull request.

**Comment by skylarCai** [comment]
Security Check : 13a723cebadfa79666365c4a4c16b08e8d7f0efd

**Comment by skylarCai** [comment]
auto build success,number:37

**Comment by skylarCai** [comment]
autotest success,number:1070

**Review by skylarCai — COMMENTED** [review]
no security risk

**Review by yanxiaoyong-ch — COMMENTED** [review]
this looks ok for me

**Review by YiluMao — APPROVED** [review]
可以合入

**Pull request merged**
