### PR TITLE
add return value for every condition, fixed #1601

### LINKED ISSUE #1601: [Bug Report]:Not all branches have return value
Function that returns non-void is missing a return value.  Arriving at the end of a function without returning a value.

### PR DESCRIPTION
**Pull request by YiluMao**
[Detail]
Issue description:
Function that returns non-void is missing a return value
Arriving at the end of a function without returning a value.

Solution:
Add return value at the end of function.

[Verified Cases]
Build Pass: eduk1_demo
Test Pass: eduk1_demo

Signed-off-by: Yilu Mao <yilu.myl@alibaba-inc.com>

### CODE REVIEW

**Comment by skylarCai** [comment]
感谢提交 Pull Requests！
Thanks for submitting a pull request.

**Comment by skylarCai** [comment]
Security Check : 1364469afddfd807f01bad336835caccce7d4e15

**Comment by skylarCai** [comment]
auto build success,number:91

**Comment by skylarCai** [comment]
autotest success,number:1189

**Review by qisheng-seu — APPROVED** [review]

**Review by qisheng-seu — COMMENTED** [review]
Approve

**Review by skylarCai — COMMENTED** [review]
no security risk

**Pull request merged**
