### PR TITLE
boards

### PR DESCRIPTION
**Pull request by ethanlcz**

### CODE REVIEW

**Comment by skylarCai** [comment]
感谢提交 Pull Requests！
Thanks for submitting a pull request.

**Comment by skylarCai** [comment]
Security Check : db0289d5435148f4064eae93c586c1185126dda3

**Review by wzhiyuan-nit — APPROVED** [review]

**Comment by skylarCai** [comment]
auto build success,number:260

**Comment by skylarCai** [comment]
autotest fail,number:1804

**Review by wzhiyuan-nit — APPROVED** [review]

**Pull request merged**
