### PR TITLE
IssueID:1526:improve flash driver framework

### PR DESCRIPTION
**Pull request by wuxn9999**
[Detail]
Improve flash driver framework.

[Verified Cases]
Build Pass: <helloworld_demo@haaseduk1>
Test Pass: <helloworld_demo@haaseduk1>

### CODE REVIEW

**Comment by skylarCai** [comment]
感谢提交 Pull Requests！
Thanks for submitting a pull request.

**Comment by skylarCai** [comment]
Security Check : 83d94eb77d71ae77976ceaabb1d8501c9028e7f1

**Comment by skylarCai** [comment]
auto build success,number:42

**Review by victorwangstone — APPROVED** [review]

**Review by victorwangstone — APPROVED** [review]
this improvement path looks fine to me, approve to merge it

**Pull request merged**
