### PR TITLE
rtl872xd: add README.md, fix #1705

### PR DESCRIPTION
**Pull request by jinliangli**
[Detail]
Add README.md

[Verified Cases]
Build Pass: <py_engine_demo>
Test Pass:  <py_engine_demo>

### CODE REVIEW

**Review by yanxiaoyong-ch — COMMENTED** [review]
this looks ok for me

**Comment by skylarCai** [comment]
start build

**Comment by skylarCai** [comment]
手动触发！
感谢 Pull Requests！
Thanks for submitting a pull request.

**Comment by skylarCai** [comment]
Security Check : 5dbd3d1f2fb2ffd4cfbfeeb05c1f70e2c4ebdc8a

**Review by skylarCai — COMMENTED** [review]
no security risk

**Review by skylarCai — COMMENTED** [review]
no security risk

**Pull request merged**
