### PR TITLE
add motion API description document

### PR DESCRIPTION
**Pull request by ethanlcz**

### CODE REVIEW

**Comment by skylarCai** [comment]
感谢提交 Pull Requests！
Thanks for submitting a pull request.

**Comment by skylarCai** [comment]
Security Check : 470dff36aea2ade823829397c953559dc61881f4

**Comment by skylarCai** [comment]
auto build success,number:54

**Comment by skylarCai** [comment]
autotest success,number:1092

**Review by kevin-alibaba — APPROVED** [review]
checked

**Pull request merged**
