### PR TITLE
IssueID:1570: vfs supports rootdir.

### PR DESCRIPTION
**Pull request by yanxiaoyong-ch**
[Detail]
none

[Verified Cases]
Build Pass: <none>
Test Pass: <none>

### CODE REVIEW

**Comment by skylarCai** [comment]
感谢提交 Pull Requests！
Thanks for submitting a pull request.

**Comment by skylarCai** [comment]
auto build success,number:77

**Comment by skylarCai** [comment]
autotest fail,number:1147

**Comment by jinliangli** [comment]
looks good.

**Pull request merged**
