### PR TITLE
add return value check when calling sensor_i2c_close, fixed #1553

### LINKED ISSUE #1553: return value is not checked when calling sensor_i2c_close
In file hardware/board/haaseduk1/config/board.c
Calling "sensor_i2c_close" without checking return value

### PR DESCRIPTION
**Pull request by YiluMao**
To prevent potential failure, we need to add return value check.

Signed-off-by: yilu.myl <yilu.myl@alibaba-inc.com>

### CODE REVIEW

**Comment by skylarCai** [comment]
感谢提交 Pull Requests！
Thanks for submitting a pull request.

**Comment by skylarCai** [comment]
Security Check : ab78a4353510fe605569a659d5137b2babdc2303

**Comment by skylarCai** [comment]
auto build fail,number:64

**Comment by skylarCai** [comment]
auto build fail,number:64

**Review by jinliangli — APPROVED** [review]
Looks good for me.

**Comment by skylarCai** [comment]
start build

**Comment by skylarCai** [comment]
手动触发！
感谢 Pull Requests！
Thanks for submitting a pull request.

**Comment by skylarCai** [comment]
Security Check : 888e7169220163057dcc9eda762296c11a53e1d9

**Comment by skylarCai** [comment]
auto build success,number:66

**Comment by skylarCai** [comment]
autotest success,number:1130

**Review by skylarCai — COMMENTED** [review]
no security risk

**Pull request merged**
