### PR TITLE
IssueID: 1560: lvgl stack decrease from 40KB to 4KB and modify lvgl s…

### PR DESCRIPTION
**Pull request by yanxiaoyong-ch**
…chedule api.

[Detail]
none

[Verified Cases]
Build Pass: <none>
Test Pass: <none>

### CODE REVIEW

**Comment by skylarCai** [comment]
感谢提交 Pull Requests！
Thanks for submitting a pull request.

**Comment by skylarCai** [comment]
Security Check : dd9a4142514496f18d6ad8b1e4c677a74f9c6b19

**Comment by skylarCai** [comment]
auto build success,number:69

**Comment by skylarCai** [comment]
autotest success,number:1133

**Review by YiluMao — APPROVED** [review]
Approve to merge

**Review by skylarCai — COMMENTED** [review]
no security risk

**Pull request merged**
