### PR TITLE
issue:1551: fix linksdk、ota、netmgr‘s whitescan error.

### PR DESCRIPTION
**Pull request by yanxiaoyong-ch**
[Detail]
none

[Verified Cases]
Build Pass: <none>
Test Pass: <none>

### CODE REVIEW

**Comment by skylarCai** [comment]
感谢提交 Pull Requests！
Thanks for submitting a pull request.

**Review by jinliangli — APPROVED** [review]
Looks good for me.

**Comment by skylarCai** [comment]
start build

**Comment by skylarCai** [comment]
手动触发！
感谢 Pull Requests！
Thanks for submitting a pull request.

**Comment by skylarCai** [comment]
Security Check : 8c66e29aa084b0ffd7081eec7819d044c6efdf5b

**Comment by skylarCai** [comment]
auto build success,number:63

**Comment by skylarCai** [comment]
autotest success,number:1126

**Review by skylarCai — COMMENTED** [review]
no security risk

**Pull request merged**
