### PR TITLE
provide hx710 sensor for driver and document

### PR DESCRIPTION
**Pull request by wushengtws**
Signed-off-by: wusheng.tws <wusheng.tws@alibaba-inc.com>

### CODE REVIEW

**Comment by skylarCai** [comment]
感谢提交 Pull Requests！
Thanks for submitting a pull request.

**Comment by skylarCai** [comment]
Security Check : d4ccdeda6f47bb0d4d6c7eaf62fb5c039996f9d3

**Comment by skylarCai** [comment]
auto build success,number:47

**Comment by skylarCai** [comment]
autotest success,number:1084

**Review by ethanlcz — APPROVED** [review]
looks good to me

**Review by skylarCai — COMMENTED** [review]
no security risk

**Pull request merged**
