### PR TITLE
stm32 startup

### PR DESCRIPTION
**Pull request by ethanlcz**

### CODE REVIEW

**Comment by skylarCai** [comment]
感谢提交 Pull Requests！
Thanks for submitting a pull request.

**Comment by skylarCai** [comment]
start build

**Comment by skylarCai** [comment]
手动触发！
感谢 Pull Requests！
Thanks for submitting a pull request.

**Comment by skylarCai** [comment]
Security Check : 629185d4fac710f403a6de62295ed773dd06da88

**Comment by skylarCai** [comment]
auto build success,number:259

**Comment by skylarCai** [comment]
autotest fail,number:1803

**Review by wzhiyuan-nit — APPROVED** [review]

**Pull request merged**
