### PR TITLE
IssueID:1574:Improve UART driver framework.

### PR DESCRIPTION
**Pull request by wuxn9999**
[Detail]
New VFS/POSIX APIs.
New userspace support.

[Verified Cases]
Build Pass: <helloworld_demo@haaseduk1>
Test Pass: <helloworld_demo@haaseduk1>

### CODE REVIEW

**Comment by skylarCai** [comment]
感谢提交 Pull Requests！
Thanks for submitting a pull request.

**Comment by skylarCai** [comment]
start build

**Comment by skylarCai** [comment]
手动触发！
感谢 Pull Requests！
Thanks for submitting a pull request.

**Comment by skylarCai** [comment]
Security Check : 08b917cf0954351893925200b8de31e5f9c3fc06

**Comment by skylarCai** [comment]
auto build success,number:80

**Comment by skylarCai** [comment]
autotest success,number:1154

**Review by skylarCai — COMMENTED** [review]
no security risk

**Review by skylarCai — COMMENTED** [review]
no security risk

**Review by victorwangstone — APPROVED** [review]
UART driver framework is correctly improved

**Review by YiluMao — APPROVED** [review]
Looks good to me.

**Pull request merged**
