### PR TITLE
IssueID:1580:HaaS200 flash driver for new driver framework

### PR DESCRIPTION
**Pull request by wuxn9999**
[Detail]
HaaS200 flash driver for new driver framework.

[Verified Cases]
Build Pass: helloworld_demo@haas200
Test Pass: helloworld_demo@haas200

### CODE REVIEW

**Comment by skylarCai** [comment]
感谢提交 Pull Requests！
Thanks for submitting a pull request.

**Comment by skylarCai** [comment]
Security Check : 80a5d4c5c5df12d24e451b1a42e66d254c5cb553

**Comment by skylarCai** [comment]
auto build success,number:84

**Comment by skylarCai** [comment]
autotest success,number:1161

**Review by skylarCai — COMMENTED** [review]
no security risk

**Review by victorwangstone — APPROVED** [review]
this new version of haas200 flahs driver looks good to me

**Review by YiluMao — APPROVED** [review]
It's ok

**Pull request merged**
