### PR TITLE
IssueID:1582:OTA supports new flash API

### PR DESCRIPTION
**Pull request by wuxn9999**
[Detail]
OTA supports new flash API.

[Verified Cases]
Build Pass: helloworld_demo@haas200
Test Pass: helloworld_demo@haas200

### CODE REVIEW

**Comment by skylarCai** [comment]
感谢提交 Pull Requests！
Thanks for submitting a pull request.

**Comment by skylarCai** [comment]
Security Check : a692cf2a52ee2094fa7ff07556113d32577a70a2

**Comment by skylarCai** [comment]
auto build success,number:85

**Comment by skylarCai** [comment]
autotest success,number:1162

**Review by yanxiaoyong-ch — COMMENTED** [review]
this looks ok for me

**Review by skylarCai — COMMENTED** [review]
no security risk

**Pull request merged**
