### PR TITLE
IssueID:1541:new VFS support and userspace support

### PR DESCRIPTION
**Pull request by wuxn9999**
[Detail]
GPIO pin APIs.
New VFS support.
Userspace support.
Output feedback support.

[Verified Cases]
Build Pass: <helloworld_demo@haaseduk1>
Test Pass: <helloworld_demo@haaseduk1>

### CODE REVIEW

**Comment by skylarCai** [comment]
感谢提交 Pull Requests！
Thanks for submitting a pull request.

**Comment by skylarCai** [comment]
Security Check : 60d00368da089a2209a40f588e2708d0714d2e50

**Comment by skylarCai** [comment]
auto build success,number:58

**Comment by skylarCai** [comment]
autotest success,number:1109

**Review by YiluMao — APPROVED** [review]
Looks good to me.

**Comment by wuxn9999** [comment]
刚才误操作了。

**Review by skylarCai — COMMENTED** [review]
no security risk

**Pull request merged**
