### PR TITLE
linksdk: improve log

### PR DESCRIPTION
**Pull request by jinliangli**
[Detail]
improve log with ulog system

[Verified Cases]
Build Pass: <py_engine_demo>
Test Pass:  <py_engine_demo>

### CODE REVIEW

**Comment by skylarCai** [comment]
感谢提交 Pull Requests！
Thanks for submitting a pull request.

**Comment by skylarCai** [comment]
Security Check : 0d8417cde98afea040be5426b0fcdfa21f9e5d26

**Comment by skylarCai** [comment]
auto build success,number:234

**Comment by skylarCai** [comment]
autotest fail,number:1738

**Review by yanxiaoyong-ch — COMMENTED** [review]
this looks ok for me

**Pull request merged**
