### PR TITLE
support network interface for haaseduk1 #1642

### PR DESCRIPTION
**Pull request by zy20220224**

### CODE REVIEW

**Comment by skylarCai** [comment]
感谢提交 Pull Requests！
Thanks for submitting a pull request.

**Comment by skylarCai** [comment]
start build

**Comment by skylarCai** [comment]
手动触发！
感谢 Pull Requests！
Thanks for submitting a pull request.

**Comment by skylarCai** [comment]
Security Check : 2022dd9e05f01bf263b115abdbdddc3de83d71fd

**Comment by skylarCai** [comment]
auto build success,number:137

**Comment by skylarCai** [comment]
autotest success,number:1346

**Review by yong171966 — COMMENTED** [review]
Looks good to me, approved

**Review by skylarCai — COMMENTED** [review]
no security risk

**Pull request merged**
