### PR TITLE
fix HaaS 200 build issue, fixed #1917

### LINKED ISSUE #1917: [Bug Report]: 最新代码编译HaaS 200的py_engine_demo solution编译失败
### 联系方式

_No response_

### 您发现了什么问题

最新代码编译HaaS 200的py_engine_demo solution编译失败

### 分支

master (Default)

### 请选择您发现此问题的解决方案名称

_No response_

### 日志

```shell
编译mod_network过不了
```

### PR DESCRIPTION
**Pull request by YiluMao**

### CODE REVIEW

**Comment by skylarCai** [comment]
感谢提交 Pull Requests！
Thanks for submitting a pull request.

**Comment by YiluMao** [comment]
start build

**Comment by skylarCai** [comment]
手动触发！
感谢 Pull Requests！
Thanks for submitting a pull request.

**Comment by skylarCai** [comment]
Security Check : ce23fbf68e11fd46a41e45584c84572c94a2ed92

**Comment by skylarCai** [comment]
auto build success,number:273

**Pull request merged**
