### PR TITLE
add wilc1000 WiFi module support on SAME54 platform

### PR DESCRIPTION
**Pull request by benpoon-microchip**
- add wilc1000 Wi-Fi module host driver and SDIO driver to SAME54 MCU
- change clk from 48MHz to 120MHz

### CODE REVIEW

**Comment by benpoon-microchip** [comment]
@librae8226

What is the status of this pull request?
Can it merge to developer branch?

Thanks

**Comment by xiaowenxia** [comment]
@benpoon-microchip The pull request is running very well, but we found this pull request modified the `kernel/protocols/net/core/pbuf.c`,  In principle we do not recommend modifying the kernel code, can you changes SDIO driver instand of pbuf.c ?

**Comment by benpoon-microchip** [comment]
@xiaowenxia 
Thanks. I will modify the code and fallback the changes in kernel code.
I will submit the pull request again later.

Thanks
Ben

**Comment by benpoon-microchip** [comment]
@xiaowenxia 
I create a new PR (#717) for this request.
Please help to check.
Thanks

**Pull request closed without merging**
