### PR TITLE
IssueID:1651: modify uln2003 input from pullup to pushpull.

### PR DESCRIPTION
**Pull request by yanxiaoyong-ch**
[Detail]
none

[Verified Cases]
Build Pass:<none>
Test Pass: <none>

### CODE REVIEW

**Comment by skylarCai** [comment]
感谢提交 Pull Requests！
Thanks for submitting a pull request.

**Comment by skylarCai** [comment]
Security Check : c5a412677c6a1965667a330ad9ac0b9d79a265e5

**Comment by skylarCai** [comment]
auto build success,number:127

**Comment by skylarCai** [comment]
autotest fail,number:1317

**Review by jinliangli — APPROVED** [review]
Looks good

**Review by skylarCai — COMMENTED** [review]
no security risk

**Pull request merged**
