### PR TITLE
change the function return as void, fixed #1599

### LINKED ISSUE #1599: aos_putchar has no return value
Function that returns non-void is missing a return value.  Arriving at the end of a function without returning a value.

### PR DESCRIPTION
**Pull request by YiluMao**
Change the function as void return since it is same in linux adapter

### CODE REVIEW

**Comment by skylarCai** [comment]
感谢提交 Pull Requests！
Thanks for submitting a pull request.

**Comment by skylarCai** [comment]
auto build success,number:90

**Review by jinliangli — APPROVED** [review]
looks good

**Review by skylarCai — COMMENTED** [review]
no security risk

**Pull request merged**
