### PR TITLE
remove bk7231s usb related file.

### PR DESCRIPTION
**Pull request by yanxiaoyong-ch**

### CODE REVIEW

**Comment by skylarCai** [comment]
感谢提交 Pull Requests！
Thanks for submitting a pull request.

**Comment by skylarCai** [comment]
start build

**Comment by skylarCai** [comment]
手动触发！
感谢 Pull Requests！
Thanks for submitting a pull request.

**Comment by skylarCai** [comment]
auto build fail,number:97

**Comment by skylarCai** [comment]
auto build fail,number:97

**Comment by skylarCai** [comment]
auto build fail,number:97

**Comment by skylarCai** [comment]
Security Check : 2943617880338621282a550a694d45168fb13500

**Review by jinliangli — APPROVED** [review]
Looks good.

**Pull request merged**
