### PR TITLE
IssueID:1700:Workaround for ethernet spi hardware

### PR DESCRIPTION
**Pull request by wuxn9999**
[Detail]
Workaround for ethernet spi hardware to prevent dead loops.

[Verified Cases]
Build Pass: <helloworld_demo@haas100>
Test Pass: <helloworld_demo@haas100>

### CODE REVIEW

**Comment by skylarCai** [comment]
感谢提交 Pull Requests！
Thanks for submitting a pull request.

**Comment by skylarCai** [comment]
Security Check : 1b6793de2cd26be6cbb3df122afb162c504f191d

**Comment by skylarCai** [comment]
auto build success,number:199

**Comment by skylarCai** [comment]
autotest fail,number:1535

**Review by yanxiaoyong-ch — COMMENTED** [review]
this looks ok for me

**Pull request merged**
