### PR TITLE
IssueID:1909:New RTC device driver framework

### PR DESCRIPTION
**Pull request by wuxn9999**
[Detail]
New RTC device driver framework.

[Verified Cases]
Build Pass: helloworld_demo@haaseduk1
Test Pass: helloworld_demo@haaseduk1

### CODE REVIEW

**Comment by skylarCai** [comment]
感谢提交 Pull Requests！
Thanks for submitting a pull request.

**Comment by skylarCai** [comment]
Security Check : e38e9be0374bf002743ad9ab3df0b1e53acc2cbd

**Comment by skylarCai** [comment]
auto build fail,number:268

**Comment by YiluMao** [comment]
start build

**Comment by skylarCai** [comment]
手动触发！
感谢 Pull Requests！
Thanks for submitting a pull request.

**Comment by skylarCai** [comment]
手动触发！
感谢 Pull Requests！
Thanks for submitting a pull request.

**Comment by skylarCai** [comment]
auto build fail,number:269

**Comment by skylarCai** [comment]
手动触发！
感谢 Pull Requests！
Thanks for submitting a pull request.

**Comment by skylarCai** [comment]
Security Check : e38e9be0374bf002743ad9ab3df0b1e53acc2cbd

**Comment by YiluMao** [comment]
start build

**Comment by skylarCai** [comment]
手动触发！
感谢 Pull Requests！
Thanks for submitting a pull request.

**Comment by skylarCai** [comment]
Security Check : e38e9be0374bf002743ad9ab3df0b1e53acc2cbd

**Comment by skylarCai** [comment]
auto build success,number:274

**Pull request merged**
