### PR TITLE
provide ttp224 sensor for driver and document

### PR DESCRIPTION
**Pull request by wushengtws**
Signed-off-by: wusheng.tws <wusheng.tws@alibaba-inc.com>

### CODE REVIEW

**Comment by skylarCai** [comment]
感谢提交 Pull Requests！
Thanks for submitting a pull request.

**Comment by skylarCai** [comment]
Security Check : bfb883d1f03eb31f57a4d90e513aac3d183491e7

**Comment by skylarCai** [comment]
auto build success,number:48

**Comment by skylarCai** [comment]
autotest success,number:1085

**Review by ethanlcz — APPROVED** [review]
looks good to me.

**Review by ethanlcz — APPROVED** [review]
looks good to me.

**Review by ethanlcz — APPROVED** [review]
looks good to me.

**Review by ethanlcz — APPROVED** [review]

**Pull request merged**
