### PR TITLE
remove bk7231s usb related file.

### PR DESCRIPTION
**Pull request by yanxiaoyong-ch**

### CODE REVIEW

**Comment by skylarCai** [comment]
感谢提交 Pull Requests！
Thanks for submitting a pull request.

**Comment by skylarCai** [comment]
auto build fail,number:98

**Comment by skylarCai** [comment]
auto build fail,number:98

**Comment by skylarCai** [comment]
auto build fail,number:98

**Comment by skylarCai** [comment]
Security Check : 85777e15d2e8a53df1e0cee7a4ef411576396e88

**Review by jinliangli — APPROVED** [review]
Looks good.

**Review by skylarCai — COMMENTED** [review]
no  security risk

**Pull request merged**
