### PR TITLE
change uart doc, fix #1614

### LINKED ISSUE #1614: [Bug Report]: uart端口使用时候，出现“BOARD_MGR board_get_items failed”错误
### Contact Details

_No response_

### What happened?

A bug happened!
运行环境:
固件版本:

### Version

master (Default)

### What soultions are you seeing the problem on?

py_engine_esp32_demo

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by zy20220224**

### CODE REVIEW

**Comment by yong171966** [comment]
Looks good to me, approved

**Comment by skylarCai** [comment]
感谢提交 Pull Requests！
Thanks for submitting a pull request.

**Comment by skylarCai** [comment]
Security Check : 295a2d0eb6658d1653c0df54ebe6ff277f15ff05

**Comment by skylarCai** [comment]
auto build success,number:102

**Review by skylarCai — COMMENTED** [review]
no security risk

**Review by yong171966 — COMMENTED** [review]
looks good to me

**Comment by skylarCai** [comment]
autotest fail,number:1216

**Pull request merged**
