### PR TITLE
add ulinksdk

### PR DESCRIPTION
**Pull request by victorwangstone**
add ulinksdk

### CODE REVIEW

**Comment by skylarCai** [comment]
感谢提交 Pull Requests！
Thanks for submitting a pull request.

**Comment by skylarCai** [comment]
auto build fail,number:216

**Comment by skylarCai** [comment]
Security Check : 0423e15fdcee2b0d0f85530c7198938c0e6c04b8

**Review by yong171966 — COMMENTED** [review]
looks good to me, approved

**Comment by skylarCai** [comment]
Security Check : 3df01cbc1b21ada8b2c4363ffb68d93e5dc3d83b

**Review by skylarCai — COMMENTED** [review]
please resolve risk problems

**Review by skylarCai — APPROVED** [review]
APPROVE

**Pull request merged**
