### PR TITLE
provide htb485 module for driver and document

### PR DESCRIPTION
**Pull request by wushengtws**
Signed-off-by: wusheng.tws <wusheng.tws@alibaba-inc.com>

### CODE REVIEW

**Comment by skylarCai** [comment]
感谢提交 Pull Requests！
Thanks for submitting a pull request.

**Comment by skylarCai** [comment]
start build

**Comment by skylarCai** [comment]
Security Check : 53f133a10ec3392e8ccf7f81d5ad6748034a0b4d

**Comment by skylarCai** [comment]
autotest success,number:1087

**Review by ethanlcz — APPROVED** [review]
looks good to me.

**Review by ethanlcz — APPROVED** [review]
looks good to me.

**Review by skylarCai — COMMENTED** [review]
no security risk

**Pull request merged**
