### PR TITLE
oss: add oss python module

### PR DESCRIPTION
**Pull request by jinliangli**
[Detail]
- Add oss python module
- Remove oss c module

### CODE REVIEW

**Comment by skylarCai** [comment]
感谢提交 Pull Requests！
Thanks for submitting a pull request.

**Comment by skylarCai** [comment]
Security Check : 085f6ebcdcceb46c4f03f01d40832a9662e9e760

**Comment by skylarCai** [comment]
auto build fail,number:236

**Comment by skylarCai** [comment]
auto build fail,number:237

**Comment by skylarCai** [comment]
auto build fail,number:241

**Comment by skylarCai** [comment]
Security Check : 085f6ebcdcceb46c4f03f01d40832a9662e9e760

**Review by yanxiaoyong-ch — COMMENTED** [review]
this looks for me

**Review by yanxiaoyong-ch — COMMENTED** [review]
this looks ok for me

**Pull request merged**
