### PR TITLE
IssueID:#1633: add temp_humidity_speaker example

### PR DESCRIPTION
**Pull request by jinliangli**
[Detail]
add temp_humidity_speaker example

[Verified Cases]
Build Pass: <py_engine_demo>
Test Pass:  <py_engine_demo>

### CODE REVIEW

**Comment by skylarCai** [comment]
感谢提交 Pull Requests！
Thanks for submitting a pull request.

**Review by YiluMao — APPROVED** [review]
Looks good to me

**Comment by skylarCai** [comment]
start build

**Comment by skylarCai** [comment]
手动触发！
感谢 Pull Requests！
Thanks for submitting a pull request.

**Comment by skylarCai** [comment]
Security Check : 707993b57473dd889d3c54f5d5ca378996bd9bef

**Comment by skylarCai** [comment]
auto build success,number:120

**Review by YiluMao — APPROVED** [review]
Looks good to me

**Comment by skylarCai** [comment]
autotest success,number:1283

**Review by yanxiaoyong-ch — COMMENTED** [review]
this looks ok for me

**Review by skylarCai — COMMENTED** [review]
no security risk

**Review by yanxiaoyong-ch — COMMENTED** [review]
this looks ok for me

**Pull request merged**
