### PR TITLE
IssueID:1778:fix python time.sleep occupying cpu on haas.

### PR DESCRIPTION
**Pull request by yanxiaoyong-ch**
[Detail]
none

[Verified Cases]
Build Pass: <none>
Test Pass: <none>

### CODE REVIEW

**Comment by skylarCai** [comment]
感谢提交 Pull Requests！
Thanks for submitting a pull request.

**Comment by skylarCai** [comment]
auto build fail,number:192

**Comment by skylarCai** [comment]
Security Check : 12b8cd5492cccab747854eff21953afd113b5035

**Review by jinliangli — APPROVED** [review]
ok

**Comment by skylarCai** [comment]
auto build success,number:196

**Comment by skylarCai** [comment]
autotest fail,number:1532

**Pull request closed without merging**
