### PR TITLE
BugID: #1872:Add color sorter demo

### PR DESCRIPTION
**Pull request by joxhehe**
[Detail]
Requirement description:
When objects of different colors are mixed together, separate them according to their colors is difficult.
Solution:
Based on esp32 board,we use tcs34725 color sensor to sort different color and we can see the statistic data on web application.

[Verified Cases]
Build Pass: py_engine_esp32_demo
Test Pass: esp32 demo

### CODE REVIEW

**Comment by skylarCai** [comment]
感谢提交 Pull Requests！
Thanks for submitting a pull request.

**Comment by skylarCai** [comment]
Security Check : 1315bfa2be70ef7bfb5d46a9bbb6ae71ad25b546

**Comment by skylarCai** [comment]
auto build success,number:248

**Review by ethanlcz — APPROVED** [review]
looks good to me.

**Pull request merged**
