### PR TITLE
support sntp interface. #1657

### PR DESCRIPTION
**Pull request by zy20220224**

### CODE REVIEW

**Comment by skylarCai** [comment]
感谢提交 Pull Requests！
Thanks for submitting a pull request.

**Comment by skylarCai** [comment]
Security Check : 9ba2f1c322c832bd4bfafa82d6b4491f84df9791

**Comment by skylarCai** [comment]
auto build success,number:136

**Comment by skylarCai** [comment]
autotest success,number:1341

**Review by yong171966 — COMMENTED** [review]
Looks good to me, approved

**Pull request merged**
