### PR TITLE
haas200: disable haas200 debug log

### PR DESCRIPTION
**Pull request by jinliangli**
[Detail]
Disable haas200  debug log

[Verified Cases]
Build Pass: <py_engine_demo>
Test Pass:  <py_engine_demo>

### CODE REVIEW

**Comment by skylarCai** [comment]
感谢提交 Pull Requests！
Thanks for submitting a pull request.

**Comment by skylarCai** [comment]
start build

**Comment by skylarCai** [comment]
手动触发！
感谢 Pull Requests！
Thanks for submitting a pull request.

**Comment by skylarCai** [comment]
手动触发！
感谢 Pull Requests！
Thanks for submitting a pull request.

**Comment by skylarCai** [comment]
Security Check : e42b165eea44760f601d4143491b450b0efd02d5

**Comment by skylarCai** [comment]
auto build success,number:238

**Comment by skylarCai** [comment]
autotest fail,number:1746

**Review by yanxiaoyong-ch — COMMENTED** [review]
this looks ok for me

**Pull request merged**
