### PR TITLE
add HaaS Python application remote upgrade SOP

### PR DESCRIPTION
**Pull request by ethanlcz**

### CODE REVIEW

**Comment by skylarCai** [comment]
感谢提交 Pull Requests！
Thanks for submitting a pull request.

**Comment by skylarCai** [comment]
Security Check : 610cd0194741d84c30da20d5485e80458a2dffab

**Comment by skylarCai** [comment]
auto build success,number:68

**Comment by skylarCai** [comment]
autotest success,number:1132

**Review by ethanlcz — COMMENTED** [review]
patch was already verified

**Pull request merged**
