### PR TITLE
provide zzio606 module for driver and document

### PR DESCRIPTION
**Pull request by wushengtws**
Signed-off-by: wusheng.tws <wusheng.tws@alibaba-inc.com>

### CODE REVIEW

**Comment by skylarCai** [comment]
感谢提交 Pull Requests！
Thanks for submitting a pull request.

**Comment by skylarCai** [comment]
Security Check : 239aaaac3b2eff58557be1003cda21f94b832be2

**Comment by skylarCai** [comment]
auto build success,number:49

**Comment by skylarCai** [comment]
autotest success,number:1086

**Review by ethanlcz — APPROVED** [review]
looks good to me

**Review by ethanlcz — COMMENTED** [review]
是不是少了一些图片?

**Review by skylarCai — COMMENTED** [review]
no security risk

**Pull request merged**
