### PR TITLE
IssueID:1728:esp32(m5stackcore2) supports sd card.

### PR DESCRIPTION
**Pull request by yanxiaoyong-ch**
[Detail]
none

[Verified Cases]
Build Pass: <py_engine_esp32_demo>
Test Pass: <py_engine_esp32_demo>

### CODE REVIEW

**Comment by skylarCai** [comment]
感谢提交 Pull Requests！
Thanks for submitting a pull request.

**Comment by skylarCai** [comment]
Security Check : c67be05c1ab5cd7393819709c20ccd4b1aaf5ef9

**Comment by skylarCai** [comment]
auto build success,number:171

**Review by yong171966 — COMMENTED** [review]
Looks good to me, approved!

**Comment by skylarCai** [comment]
autotest success,number:1388

**Pull request merged**
