### PR TITLE
BugID:1844:Add the source code of esp32 worst-case.

### LINKED ISSUE #1844: [Feature Request]: 增加 esp32s worst case
### 联系方式

_No response_

### 新功能描述

功能描述

### 分支

master (Default)

### PR DESCRIPTION
**Pull request by wzhiyuan-nit**
[Detail]
Issue description:
Add the source code of esp32 worst-case. fixes #1844 
Rootcause:

Solution:

Requirement description:

Solution:

[Verified Cases]
Build Pass: <solution list>
Test Pass: <test case list>

Signed-off-by: wzhiyuan-nit <wuming.wzy@alibaba-inc.com>

### CODE REVIEW

**Comment by skylarCai** [comment]
感谢提交 Pull Requests！
Thanks for submitting a pull request.

**Comment by skylarCai** [comment]
Security Check : a398c36e5bc211da3bc14879a67b3d9af6e53ea7

**Comment by skylarCai** [comment]
auto build success,number:229

**Comment by skylarCai** [comment]
autotest fail,number:1722

**Review by ethanlcz — APPROVED** [review]
looks good to me.

**Pull request merged**
