### PR TITLE
IssueID:1915:Improve UART driver development document

### PR DESCRIPTION
**Pull request by wuxn9999**
[Detail]
Fix some spelling mistakes.

[Verified Cases]
Build Pass: helloworld_demo@haaseduk1
Test Pass: helloworld_demo@haaseduk1

### CODE REVIEW

**Comment by skylarCai** [comment]
感谢提交 Pull Requests！
Thanks for submitting a pull request.

**Comment by skylarCai** [comment]
Security Check : 2fa7e0c902d831e129218d55413b29c6f31a001d

**Comment by YiluMao** [comment]
start build

**Comment by skylarCai** [comment]
手动触发！
感谢 Pull Requests！
Thanks for submitting a pull request.

**Comment by skylarCai** [comment]
Security Check : 2fa7e0c902d831e129218d55413b29c6f31a001d

**Comment by skylarCai** [comment]
auto build success,number:275

**Pull request merged**
