### PR TITLE
fix haaseduk1 failed connnect network occasional when multi task connect at the same time #1752

### PR DESCRIPTION
**Pull request by zy20220224**

### CODE REVIEW

**Comment by skylarCai** [comment]
感谢提交 Pull Requests！
Thanks for submitting a pull request.

**Comment by skylarCai** [comment]
Security Check : ad987dfeb2e0eba1aa2fb24630065c87bbccb4a0

**Comment by skylarCai** [comment]
auto build fail,number:181

**Review by yong171966 — COMMENTED** [review]
Looks good to me, approved!

**Comment by skylarCai** [comment]
start build

**Comment by skylarCai** [comment]
手动触发！
感谢 Pull Requests！
Thanks for submitting a pull request.

**Comment by skylarCai** [comment]
Security Check : ad987dfeb2e0eba1aa2fb24630065c87bbccb4a0

**Comment by skylarCai** [comment]
auto build fail,number:184

**Comment by skylarCai** [comment]
start build

**Comment by skylarCai** [comment]
手动触发！
感谢 Pull Requests！
Thanks for submitting a pull request.

**Comment by skylarCai** [comment]
auto build success,number:185

**Review by skylarCai — COMMENTED** [review]
no security risk

**Pull request merged**
