### PR TITLE
IssueID:1654:correct HaaSPython Uart return value.

### PR DESCRIPTION
**Pull request by yanxiaoyong-ch**
[Detail]
none

[Verified Cases]
Build Pass: <none>
Test Pass: <none>

### CODE REVIEW

**Comment by skylarCai** [comment]
Security Check : 7c4beefc86affdf63a154516c4872b30533bfa54

**Comment by skylarCai** [comment]
auto build success,number:135

**Comment by skylarCai** [comment]
autotest fail,number:1338

**Review by skylarCai — COMMENTED** [review]
no security risk

**Review by jinliangli — APPROVED** [review]
Looks good.

**Pull request merged**
