### PR TITLE
update for online upgrade

### PR DESCRIPTION
**Pull request by PiaoLingAl**

### CODE REVIEW

**Comment by skylarCai** [comment]
感谢提交 Pull Requests！
Thanks for submitting a pull request.

**Comment by skylarCai** [comment]
Security Check : 9b0f5a145a55052dabc845a4386382d3fdeb47ac

**Comment by skylarCai** [comment]
auto build success,number:133

**Comment by skylarCai** [comment]
autotest success,number:1330

**Review by yanxiaoyong-ch — COMMENTED** [review]
this looks ok for me

**Review by YiluMao — APPROVED** [review]
Approved

**Review by skylarCai — COMMENTED** [review]
no security risk

**Pull request merged**
