### PR TITLE
create driver and api for the fheartbeat sensor #1660

### PR DESCRIPTION
**Pull request by wushengtws**

### CODE REVIEW

**Comment by skylarCai** [comment]
感谢提交 Pull Requests！
Thanks for submitting a pull request.

**Comment by skylarCai** [comment]
Security Check : c496d999ffc08331be32c2dec83c57ceea49e2e2

**Comment by skylarCai** [comment]
auto build success,number:131

**Comment by skylarCai** [comment]
autotest fail,number:1324

**Review by ethanlcz — APPROVED** [review]
looks good to me.

**Review by skylarCai — COMMENTED** [review]
no security risk

**Pull request merged**
