### PR TITLE
IssueId:1647: add delivery_track example of nodemcu32s.

### PR DESCRIPTION
**Pull request by yanxiaoyong-ch**
[Detail]
none

[Verified Cases]
Build Pass: <none>
Test Pass: <none>

### CODE REVIEW

**Comment by skylarCai** [comment]
Security Check : 1b09f055f868e7e8c497b3146a3aa4e0c203f2eb

**Comment by skylarCai** [comment]
auto build success,number:125

**Comment by skylarCai** [comment]
autotest success,number:1308

**Review by YiluMao — APPROVED** [review]
Looks good to me

**Review by jinliangli — APPROVED** [review]
good python example

**Review by skylarCai — COMMENTED** [review]
no security risk

**Pull request merged**
