### PR TITLE
IPX DPS310 pressure sensor porting

### PR DESCRIPTION
**Pull request by DonaldLeungIfx**
This driver might not work after you connect the Infineon DPS310 sensor onto the development board, as it uses the external I2C port #3, and I2C port #3 is not yet working on the master branch.

I tested this driver on the following commit, this particular commit uses a base that the external I2C port #3 is working.

https://github.com/DonaldLeungIfx/AliOS-Things/commit/ac915fc559004aaef777195e51fe48949cf54919

Signed-off-by: Donald Leung <donald.leung@infineon.com>

### CODE REVIEW

**Comment by librae8226** [comment]
Thanks for contributing!
Would you please sign the [CLA](https://cla-assistant.io/alibaba/AliOS-Things) above?

**Comment by DonaldLeungIfx** [comment]
@librae8226 , yes, now our legal team is evaluating the CLA

**Comment by DonaldLeungIfx** [comment]
@Cheng-SG , @librae8226 , I wonder what is the following "check coding style failed" error is about..? I wonder which part of the code has a coding style issue. Thanks.

"check coding style failed; autofix failed: can not push fix commit to repo git@github.com:alibaba/AliOS-Things.git"

**Comment by DonaldLeungIfx** [comment]
As the legal CLA is still under process, at the moment I would need to close this pull request.

**Pull request closed without merging**
