### PR TITLE
add motion detection API's example

### PR DESCRIPTION
**Pull request by ethanlcz**

### CODE REVIEW

**Comment by skylarCai** [comment]
Security Check : e631b725ade50ec01d71c0b8c21989dbd9477f47

**Review by ethanlcz — COMMENTED** [review]
This example uses motion detection API.

**Comment by skylarCai** [comment]
auto build success,number:70

**Comment by skylarCai** [comment]
autotest success,number:1135

**Review by skylarCai — COMMENTED** [review]
no security risk

**Review by kevin-alibaba — COMMENTED** [review]
checked

**Pull request merged**
