### PR TITLE
IssueID:1684:Python example power meter

### PR DESCRIPTION
**Pull request by wuxn9999**
[Detail]
New Python example: power meter.

[Verified Cases]
Build Pass: <py_engine_demo>
Test Pass:  <py_engine_demo>

### CODE REVIEW

**Comment by skylarCai** [comment]
感谢提交 Pull Requests！
Thanks for submitting a pull request.

**Review by yanxiaoyong-ch — COMMENTED** [review]
this looks ok for me

**Comment by skylarCai** [comment]
auto build success,number:151

**Review by skylarCai — COMMENTED** [review]
no security risk

**Pull request merged**
