### PR TITLE
add m5stackcore2 demo-smart_traffic_light,fixes #1640

### LINKED ISSUE #1640: [Feature Request]: add m5stackcore2 demo-smart_traffic_light
### Contact Details

_No response_

### What do you want?

feature request

### Version

master (Default)

### PR DESCRIPTION
**Pull request by ZH-21000301**

### CODE REVIEW

**Review by kevin-alibaba — COMMENTED** [review]
checked

**Comment by skylarCai** [comment]
Security Check : 48112ed98966808ff8be3041a18526d72630c7ad

**Comment by skylarCai** [comment]
auto build success,number:121

**Comment by skylarCai** [comment]
autotest success,number:1291

**Review by skylarCai — COMMENTED** [review]
no security risk

**Pull request merged**
