### PR TITLE
fix uart.on() failed  # 1584

### PR DESCRIPTION
**Pull request by zy20220224**

### CODE REVIEW

**Comment by skylarCai** [comment]
感谢提交 Pull Requests！
Thanks for submitting a pull request.

**Comment by skylarCai** [comment]
auto build fail,number:100

**Comment by skylarCai** [comment]
Security Check : 4d63cf1ce487cdd7d1b4fdc3fdbfe930d4dce305

**Comment by skylarCai** [comment]
auto build success,number:101

**Comment by skylarCai** [comment]
autotest fail,number:1213

**Comment by yong171966** [comment]
Looks good to me, approved

**Review by yong171966 — COMMENTED** [review]
Looks good to me

**Pull request merged**
