### PR TITLE
update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by skylarCai**

### CODE REVIEW

**Comment by skylarCai** [comment]
感谢提交 Pull Requests！
Thanks for submitting a pull request.

**Comment by skylarCai** [comment]
Security Check : 8aeaa41318efbbf8a5d1d9f4134148f336964bcc

**Review by yanxiaoyong-ch — COMMENTED** [review]
this looks ok for me

**Comment by skylarCai** [comment]
auto build success,number:88

**Comment by skylarCai** [comment]
autotest success,number:1170

**Pull request merged**
