### PR TITLE
add traker rockerkey ws2812 motorspeed driver and api for new sensors #1662

### PR DESCRIPTION
**Pull request by wushengtws**

### CODE REVIEW

**Comment by skylarCai** [comment]
感谢提交 Pull Requests！
Thanks for submitting a pull request.

**Comment by skylarCai** [comment]
Security Check : fb95dbcdbb30975437d0e3570d727d41631747fd

**Comment by skylarCai** [comment]
auto build success,number:132

**Review by skylarCai — COMMENTED** [review]
no security risk

**Comment by skylarCai** [comment]
autotest fail,number:1326

**Review by ethanlcz — APPROVED** [review]
looks good to me.

**Review by skylarCai — COMMENTED** [review]
no security risk

**Pull request merged**
