### PR TITLE
haas1000: disable some bsp log

### PR DESCRIPTION
**Pull request by jinliangli**
[Detail]
Disable some haas1000 bsp log

[Verified Cases]
Build Pass: <py_engine_demo>
Test Pass:  <py_engine_demo>

### CODE REVIEW

**Comment by skylarCai** [comment]
感谢提交 Pull Requests！
Thanks for submitting a pull request.

**Comment by skylarCai** [comment]
Security Check : 1225641d565cbc77d3d2f702c5943e1461baa9c8

**Comment by skylarCai** [comment]
auto build success,number:233

**Comment by skylarCai** [comment]
autotest fail,number:1736

**Review by yanxiaoyong-ch — COMMENTED** [review]
this looks ok for me

**Pull request merged**
